# Generated by Django 2.2.2 on 2019-06-29 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='duedate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('danger', '緊急'), ('info', '通常'), ('success', 'そのうち')], default='danger', max_length=50),
            preserve_default=False,
        ),
    ]
